"""Add city and locality to users

Revision ID: d17d1bb1b01a
Revises: ef18290d2953
Create Date: 2026-09-10 23:11:39.567325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17d1bb1b01a'
down_revision: Union[str, None] = 'ef18290d2953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('locality', sa.String(), nullable=True))
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.add_column('workers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('locality', sa.String(), nullable=True))
    op.drop_column('workers', 'longitude')
    op.drop_column('workers', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.drop_column('workers', 'locality')
    op.drop_column('workers', 'city')
    op.add_column('users', sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.drop_column('users', 'locality')
    op.drop_column('users', 'city')
    op.drop_table('verification_documents')
    # ### end Alembic commands ###
